### ISSUE TITLE
请问您的代码有相关的论文吗

### ISSUE THREAD

**Issue by zhao1999shuai** [GuoHaoren/Implementation-of-GCU-Transformer-for-RUL-Prediction-on-CMAPSS#5]

**Comment by zhao1999shuai** [comment]
我已经看到您的readme上面有论文了，但是我不知道怎么删掉这个问题，不好意思

**Comment by GuoHaoren** [comment]
没事，我一会儿来删就行

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zhao1999shuai ***@***.***>
发送时间: Saturday, May 18, 2024 9:31:52 AM
收件人: GuoHaoren/Implementation-of-GCU-Transformer-for-RUL-Prediction-on-CMAPSS ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [GuoHaoren/Implementation-of-GCU-Transformer-for-RUL-Prediction-on-CMAPSS] 请问您的代码有相关的论文吗 (Issue #5)

        - External Email -



我已经看到您的readme上面有论文了，但是我不知道怎么删掉这个问题，不好意思

―
